### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by PedroKim** [kelsangt/Rainier#5]
# Backend Routes

- [ ]  Contains the following sections: HTML, API Endpoints(Backend)
- [x]  Each route has a description
- [x]  API Endpoint routes contains wildcard variables written in `snake_case`
- [ ]  Routes does not contain superfluous routes
- [ ]  Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    -  probably doesn't need a `GET likes` api endpoint because that info comes through the post show

### Comments
- [ ] missing HTML section and header text for API Endpoints section
- [ ] show route for `users` is missing a wildcard
- [ ] rename `cart` routes to `cart_items`
- [ ] instead of a show route for `cart_items`, make it a nested route under `users` so you can filter cart items based off of user id. This will still be part of `cart_items` route.
- [ ] add delete route for removing cart items
- [ ] don't need separate route for reviews index. Instead, `products` show route can contain reviews that pertains to the product.
- [ ] add patch and delete routes for reviews.
- [ ] what is your motivation behind a show route for retrieving a single review?

**Comment by kelsangt** [comment]
Resolved.
